name: Build & Deploy (Astro → Webgo via FTP)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Code auschecken
      - uses: actions/checkout@v4

      # 2. PNPM installieren
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # 3. Abhängigkeiten installieren & Astro‑Build
      - name: Install deps & build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build           # erzeugt dist/

      # 4. Upload via FTP
      - name: Deploy to Webgo
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server:   ${{ secrets.FTP_HOST }}   # z. B. s135.goserver.host
          username: ${{ secrets.FTP_USERNAME }} # web67f1
          password: ${{ secrets.FTP_PASSWORD }}
          port:     ${{ secrets.FTP_PORT }}     # 21
          protocol: ftp                         # ggf. ftps
          local-dir: dist/
          server-dir: /
          dangerous-clean-slate: true           # löscht Alt‑Dateien
 